
NAME = 

CFLAGS = 

all: $(NAME)

# Rule to build your object files and link them into a binary
$(NAME):

# Rule to remove object files
clean:

# Rule to remove binary, calls the 'clean' rule first
fclean: clean

# Rule to remove object files and binary, then re-build everything
re: fclean all

# Rule to debug, include norminette and similars
test: fclean 

# Rules that are not linked with a filename should be listed here
.PHONY: all clean fclean re
