#!/bin/bash
cat ./sources/ascii.art
#install vim preferences
ln ./sources/.vimrc ~/.vimrc
# instalar oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# instalar tema over10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
#alias a la carpeta de oh-my-zsh
ln ./sources/alias.zsh ~/.oh-my-zsh/custom/alias.zsh
# general config oh-my-zsh
ln ./sources/.zshrc ~/.zshrc
# configura ignore global
ln ./sources/.gitignore_global ~/.gitignore_globalq
git config --global core.excludesfile ~/.gitignore_global
# Instala las fuentes
cp ./sources/font/*.ttf ~/Library/Fonts
# Cambia el desplazamiento del raton a no natural
defaults write ~/Library/Preferences/.GlobalPreferences.plist com.apple.swipescrolldirection -boolean NO
# instala preferencia de iTerm2
echo "No te olvides de reiniciar el terminal para aplicar todos los cambios"
exit 0
